mritchielab/GlimmaV2

inst/htmlwidgets/GlimmaV2.js
inst/htmlwidgets/GlimmaV2.yaml
inst/htmlwidgets/lib/vega/vega_plots.css

Changed the PNG save button to a generic save button that has a dropdown for PNG and SVG saving.

Added SVG saving

---

.Rhistory
R/GlimmaV2.R
inst/htmlwidgets/GlimmaV2.js
inst/htmlwidgets/lib/vega/vega_plots.css
test/TestMDS.html
test/test_MA_plot.Rmd

- going from passing ID references to directly using HTML elements, to support multiple widgets being knittable on the same page
- no ID attributes will be assigned for simplicity
- increase height of the plot to prevent markdown issues on the same line:
- dummy_element displaying in the second MDS plot, need to fix reformatElementsMDS()

Multiple plot display bug fixes

---

R/glimmaXY.R
inst/htmlwidgets/glimmaXY.js
testnotebooks/testExp.Rmd
testnotebooks/test_MA_plot.Rmd

expression plot working with
- DGELRT, DGEExact
- MArrayLM
- DESeqDataset (auto counts, groups extraction from colData)
bug fix applied for when counts is not supplied (expressionView was being called even when null).

expression plot object support

---

R/glimmaXY.R
inst/htmlwidgets/glimmaMDS.yaml
inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/glimmaXY.yaml
inst/htmlwidgets/lib/FileSaver/FileSaver.js
inst/htmlwidgets/lib/GlimmaV2/saveTools.js
inst/htmlwidgets/lib/datatables/datatables.css
inst/htmlwidgets/lib/vega/vega_plots.css
testnotebooks/testExp.Rmd

- saving selected subsets of genes
- saving counts matrix concatenated to table
- selection bubbles are grey

Save table subset

---

R/glimmaMA.R
R/glimmaVolcano.R
tests/testthat/test-glimmaMA.R
tests/testthat/test-glimmaVolcano.R
tests/testthat/test-glimmaXY.R
tests/testthat/test-helperFunctions.R

- testing widget creation and saving capabilities for all object types and plots
- testing that errors are thrown/not thrown for status, status.colours arguments
- added filtering of user-provided status argument for DESeqDataset since an error would previously be thrown if the user entered their own status vector but the DESeqDataset was filtered to remove NA rows inside the function

basic testing

---

R/glimmaMA.R
R/glimmaVolcano.R
inst/htmlwidgets/lib/GlimmaV2/expressionSpec.js
man/glimmaMA.Rd
man/glimmaMDS.DGEList.Rd
man/glimmaMDS.Rd
man/glimmaVolcano.Rd

- expression plot is coloured by group, not by the sample
- clarify in the docs that MA/Volcano plots are implementations of the base XY plot

Group colours

---

DESCRIPTION

Restoring Glimma V1 import until it can be removed from unit test.

Temporarily restored Glimma import

---

R/glimmaMDS.R
inst/htmlwidgets/glimmaMDS.js
inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/lib/GlimmaV2/saveTools.js
inst/htmlwidgets/lib/vega/vega_plots.css

- Added a dropdown for the XY plot's button to save the table. Now, the Save Data button creates a dropdown giving the options to save selected genes as well as the whole table
- Fixed an issue with the MDS plot's Save (MDS) and Save (VAR) buttons, which was create when updating the XY plots Save buttons to be a dropdown under a single button. MDS plot now has a single Save Plot button, under which the same options as before can be selected.

Save Data dropdown and MDS save button fixes

---

DESCRIPTION
R/glimmaMA.R
R/glimmaMDS.R
R/glimmaVolcano.R
R/glimmaXY.R
man/glimmaMA.DESeqDataSet.Rd
man/glimmaMA.DGEExact.Rd
man/glimmaMA.MArrayLM.Rd
man/glimmaMDS.DESeqDataSet.Rd
man/glimmaMDS.DGEList.Rd
man/glimmaMDS.Rd
man/glimmaMDS.default.Rd
man/glimmaVolcano.DESeqDataSet.Rd
man/glimmaVolcano.DGEExact.Rd
man/glimmaVolcano.Rd
man/glimmaXY.Rd
vignettes/limma_edger.Rmd

* Added examples to glimmaMA, glimmaVolcano and glimmaXY plots. At this point there should be no BiocCheck warnings except git file size.

Added examples

---

R/glimmaMDS.R
tests/testthat/test-glimmaMDS.R

Expression colourscheme

---

inst/htmlwidgets/lib/GlimmaV2/saveTools.js

fix svg bug

---

DESCRIPTION

No longer needed due to the removal of the data folder

Deleted LazyData statement in DESCRIPTION

---

R/glimmaXY.R
inst/htmlwidgets/lib/GlimmaV2/XYSpecs.js

Improved status labels

---

inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/lib/GlimmaV2/expressionSpec.js
inst/htmlwidgets/lib/vega/vega_plots.css

configurable minimum y-axis for expression plot 

---

inst/htmlwidgets/glimmaMDS.js
inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/lib/vega/vega_plots.css

Fix mds layout

---

inst/htmlwidgets/lib/GlimmaV2/XYSpecs.js

Addressing issue https://github.com/hasaru-k/GlimmaV2/issues/90

Blank plot when gene annotation only contains one column 

---

inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/lib/datatables/custom_styles.css
inst/htmlwidgets/lib/libXY/expressionSpec.js
inst/htmlwidgets/lib/libXY/xy_styles.css

Adds a `glimma_XY` prefix to classnames to avoid collisions, and removes some unused CSS rules

[XY] Cleanup class names

---

inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/glimmaXY.ts
inst/htmlwidgets/package.json
inst/htmlwidgets/yarn.lock

[XY] Typescript

---

inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/glimmaXY.ts

Prerequisite for https://github.com/mritchielab/GlimmaV2/pull/121

[XY] Add typings for R data

---

R/glimmaMA.R
R/glimmaXY.R
inst/htmlwidgets/glimmaXY.js
inst/htmlwidgets/glimmaXY.ts
inst/htmlwidgets/lib/libXY/XYSpecs.js

[XY] Scaffold multiple contrasts view

---

DESCRIPTION
inst/htmlwidgets/lib/libXY/xy_styles.css
inst/htmlwidgets/lib/vega/vega-styles.css

[XY] CSS brushups
